### PR TITLE
Floor and Round functions

### PR DESCRIPTION
**Pull request by cjllanwarne**
Because that hack is just too horrible

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1: :1st_place_medal:

**Comment by mcovarr** [comment]
with some docs over in the other repo

**Comment by Horneth** [comment]
👍

**Comment by geoffjentry** [comment]
Please add a ceiling function as well, otherwise 👍

**Comment by jmthibault79** [comment]
https://lh5.ggpht.com/0Lth0ERywfW-9-K6_pOaye3Yirqiqhcx_IMvcuV3n24JUTPnc-EvSisg2hxUsH4jN5g=w300

**Comment by jmthibault79** [comment]
ceiling cat

**Pull request merged**
