### PR TITLE
Graph Nodes as a WOM

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

**Comment by cjllanwarne** [comment]
Not really a PR right now. Will reopen later

**Comment by geoffjentry** [comment]
@cjllanwarne Is this a real PR? Strawman? Something else?

**Comment by cjllanwarne** [comment]
Diagram of what the Three Step workflow made in `GraphSpec` ends up looking like:

three step wom diagram

**Comment by cjllanwarne** [comment]
@geoffjentry I guess it's a "chance to look at and review something before it merges into the cromwomification branch, and more things get built on top of it".

I also want to add a calendar entry to demonstrate in person what's going on here.

**Pull request merged**
