### PR TITLE
Sub Workflows

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by Horneth** [comment]
Looks like all the *.html are scala docs updates due to some class renaming

**Comment by geoffjentry** [comment]
@Horneth Along with the rest of the side things which need updating can you make a PR against the spec in the wdl repo to reflect the changes? Also I think that'd be helpful in general when trying to digest the PR once everything is ready

**Comment by Horneth** [comment]
@geoffjentry Yep. I'm also not sure where / how much doc we want to generate for sub workflows in general. Is the Cromwell README still a good place (since it's currently being rewritten by Kate) ?

I think there are 2 different pieces : the WDL spec, and how Cromwell specifically executes sub workflows (or at least the user facing implications).

**Comment by geoffjentry** [comment]
@Horneth For this I'm thinking specifically the WDL spec - it came to mind when I was looking through the grammar file and such.

**Comment by cjllanwarne** [comment]
👍

**Comment by mcovarr** [comment]
beyond the noise factor, aren't the HTML changes to earlier wdl4s versions incorrect since those were in fact the names of those classes in those releases?

**Comment by Horneth** [comment]
Yes - I reverted them but forgot to push

**Comment by mcovarr** [comment]
:+1: hooray

**Pull request merged**
